### ISSUE TITLE
NullReferenceException thrown when reading from non-existent stream targeting .NET Core 2.0

### ISSUE THREAD

**Issue by jimmyheaddon** [EventStore/ClientAPI.NetCore#30]
Greetings,

Apologies if this has been raised before, or if it's a .NET Core CLR issue, but I'm experiencing NullReferenceExceptions from your .NET Core library, when awaiting `ReadEventAsync` and specifying a stream name that doesn't exist (it will, but the reader starts before the stream is written to).

The same operation behaves fine when the calling app targets .NET 4.7.1, but running as a .NET Core 2.0 app causes this repeatedly.

If you call this code using a plain old console app targeting .NET Core 2.0, then you should see what I mean:

```
var task = connection.ReadEventAsync("ThisStreamDoesNotExist", StreamPosition.End, false);

// The await below throws a NullReferenceException
var result = await task;
```

Potentially it's a Core CLR issue, but I'm having to handle this on my end, which doesn't seem right as a library returned Task should never be null, I believe?

Shout if you need me to build a repro app/record a video/whatever.

Cheers

**Comment by gregoryyoung** [comment]
Most likely this seems like an oversight and we will add a ticket to look into it. Thanks for the report.

**Comment by gregoryyoung** [comment]
Forgive me for being a bit fast but I don't see an obvious issue https://github.com/EventStore/ClientAPI.NetCore/blob/master/src/EventStore.ClientAPI.NetCore/Internal/EventStoreNodeConnection.cs#L176

Can you describe more what you are seeing and how to reproduce?

**Comment by jen20** [comment]
In particular a backtrace and core would be useful here.

**Comment by jimmyheaddon** [comment]
Well this is painful... I can make it throw repeatedly in my library code, but I can't isolate a useful repro case.  We have the above code snippet in a .NET Standard 2.0 library that is referenced from a .NET Core 2.0 console application, using Polly wrappers to handle disconnects (etc.).  I figure nested async Polly blocks might be the cause, but _typically_ it won't reproduce in a standalone app.

I'll throw the stack traces and information below, in case that's of any use, but it seems like a very edge case perhaps!

**Top Level Exception**
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=EventStore.ClientAPI.NetCore
  StackTrace:
   at EventStore.ClientAPI.ClientOperations.ReadEventOperation.InspectResponse(ReadEventCompleted response)
   at EventStore.ClientAPI.ClientOperations.OperationBase`2.InspectPackage(TcpPackage package)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
![toplevelexception](https://user-images.githubusercontent.com/944499/41237185-d7670142-6d8a-11e8-8a17-9aacb7b77623.PNG)

**Exception Details**
![exceptiondetails](https://user-images.githubusercontent.com/944499/41237187-da250348-6d8a-11e8-9fc7-8927de80b955.png)

**Call Stack**
I've redacted the top-level namespace, sorry!
![callstack](https://user-images.githubusercontent.com/944499/41237425-5d7d5e52-6d8b-11e8-9244-a5323433a147.png)

**Example Code**
Taking Polly out, this is essentially the code that throws the exception when run under a Console app targetting .NET Core 2.0 instead of .NET Framework 4.7.1:

```
const string EventStoreStreamName = "ThisStreamDoesNotExist";

var eventStoreUri = new UriBuilder("tcp", "localhost", 1113).Uri;

using (var connection = EventStoreConnection.Create(eventStoreUri, EventStoreStreamName))
{
    await connection.ConnectAsync();

    try
    {
        var result = await connection.ReadEventAsync(EventStoreStreamName, StreamPosition.End, false);

        Console.WriteLine(".NET Core doesn't reach this log statement.");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Exception thrown: {ex.Message}");
    }
}
```

**Random Details**
- EventStore.ClientAPI.NetCore v4.1.0.23
- Microsoft.NETCore.Portable.Compatibility v1.0.2
- Microsoft .NET Core SDK 2.1.4 (and multiple other versions, apparently!)
- Windows 10 v1709

**Comment by jimmyheaddon** [comment]
I'm still struggling to replicate this in a standalone app.

On another note, I've just realised that `await connection.ConnectAsync();` returns even when the connection hasn't succeeded, so you can technically call something like `await connection.ReadEventAsync()` before the connection is open, which causes an `ObjectDisposedException` to throw.  Is that to be expected?  Unfortunately there's no `.Disposed` or `.Connected` property on `IEventStoreConnection` to interrogate the status of the connection :(

**Comment by Narvalex** [comment]
I look that I have the same issue. Maybe this log taken from the EventStore.Client for .Net Core is related. It says that it can not deserialize a ProtoBuff message perhaps?

```
[12,14:44:12.667,DEBUG] Deserialization to EventStore.ClientAPI.Messages.ClientMessage+ReadEventCompleted failed : System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at ProtoBuf.Serializers.TypeSerializer.CreateInstance(ProtoReader source, Boolean includeLocalCallback) in C:\code\protobuf-net\src\protobuf-net\Serializers\TypeSerializer.cs:line 314
   at ProtoBuf.Serializers.TypeSerializer.Read(Object value, ProtoReader source) in C:\code\protobuf-net\src\protobuf-net\Serializers\TypeSerializer.cs:line 209
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type) in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 607
   at proto_12(Object , ProtoReader )
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type) in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 607
   at proto_10(Object , ProtoReader )
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 748
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 606
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in C:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 84
   at EventStore.ClientAPI.Transport.Tcp.ProtobufExtensions.Deserialize[T](ArraySegment`1 data)
```

**Comment by Narvalex** [comment]
I found that is only happens when atempting to call event store when it is warming up. It the event store instance is already running, then the error does not occur.
