### ISSUE TITLE
Closing an EventStoreConnection causes ObjectDisposedExceptions on re-use

### ISSUE THREAD

**Issue by jimmyheaddon** [EventStore/ClientAPI.NetCore#32]
Greetings

I've found what I believe might be a bug in the API, or at least a usability issue, that I'd like to raise.  When you call `EventStoreNodeConnection.ConnectAsync()` you get a `Task` returned, but the completion of this task doesn't represent the actual connection status.  This leads to race conditions (or even worse, 100% exceptions if Event Store isn't even running) when you try an operation like `ReadStreamEventsForwardAsync()`, only to receive an `ObjectDisposedException`, because the connection hasn't been established.

Currently there isn't any way to check if the connection is open, other than subscribing to the event handler, which is messy, because that callback will likely be thrown on a completely different thread to your main thread (it certainly does in my case).

I started putting together a PR to address this, but this potentially relates to the `IDisposable` implementation in `EventStoreNodeConnection`.  Bear with me...

The `IEventStoreConnection` interface inherits from `IDisposable`, but the `EventStoreNodeConnection` implementation doesn't follow the Microsoft guidelines for implementing the disposable pattern.  Therefore, if you call `Close()` on a connection (or it's terminated behind the scenes, e.g. when automatic reconnect is enabled), then you get `ObjectDisposedExceptions` thrown from the API.  This is because `EventStoreConnectionLogicHandler.CloseConnection()` itself disposes of a number of objects, which can't then be re-used until you explicitly call `Connect`, which as I mentioned, isn't always in your control!

- `EventStoreNodeConnection` would need a private field to maintain whether the instance has been disposed of
- All the public and internal methods of `EventStoreNodeConnection` would need to check the aforementioned flag, before executing
- Ideally the aforementioned private field would be a public property, so that consumers of the API can check whether they need to call reconnect themselves.  It'd be nice to expose this alongside the `Connected` property, to make this much easier to use

Thoughts?  I'd really like to use this API more reliably, but there's just too much abstracted away from view to really have a fighting chance of orchestrating the various API calls yourself.

Cheers!

**Comment by haf** [comment]
Did you ever get around to testing and implementing this?

**Comment by jimmyheaddon** [comment]
I still see this occasionally, but I can't reproduce it in a simple use case.  The stack trace is just bizarre, and points to it being an internal error with the library, but I just can't replicate it consistently

**Comment by haf** [comment]
I have a similar crash like so:

```
spns | [21:25:23 WRN] Subscription to "$et-UserAttached" lost with reason "CatchUpError". Reconnecting. <ReCQ.EventStore.CatchUpStream>
spns | System.ObjectDisposedException: Cannot access a disposed object.
spns | Object name: 'ES-983c8c79-2fb8-4d90-be4d-2612e178b5f3'.
spns | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
spns | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
spns | at EventStore.ClientAPI.EventStoreStreamCatchUpSubscription.<ReadEventsInternalAsync>d_6.MoveNext()
spns | --- End of exception stack trace ---
spns | at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
spns | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
spns | at EventStore.ClientAPI.EventStoreCatchUpSubscription.<LoadHistoricalEventsAsync>d_35.MoveNext()
```

**Comment by bboyle1234** [comment]
Doesn't the connection object raise events that you can subscribe to and track the connection status? 
Reconnecting.
Connected.
Disconnected, etc?

**Comment by theofanis** [comment]
This is something I can verify as well. But only when running my **.netcore app on linux**, for example in a docker container.

The singleton `IEventStoreConnection` is set to keep reconnecting using `KeepReconnecting()` on the settings builder.

Debugging on Windows, I kill the EventStore server (docker container) and I see my persistent subscription drops as expected. 

The `SubscriptionDropped` handler calls `subscription.Stop(TimeSpan.FromSeconds(5))`. The timeout passes and I get an error saying the subscription could not be stopped. I call `Connect` whether `Stop` succeeds or not.

 When I start the server once again, the connection reconnects and the subscription moves on with connecting as well and life goes on.

Now, **running my app in a docker container (Linux), the subscription drop handler fires, and the `subscription.Stop()` call throws the `ObjectDisposedException`**. I have never seen this behavior when running the app on Windows.

I am now at a place where I am trying to figure out having a dependency on a connection factory that always checks if the connection is disposed before creating a new one and calling `ConnectAsync()` on it. The factory uses a `SemaphoreSlim` to cover multithreaded scenarios, but even after a successful creation and connection, there is no guarantee that the object won't be disposed even milliseconds later considering a disconnection occurred in the time between. Also, this will hurt the performance of many REST API calls as well, since then the code has to get a connection by calling my factory, so going through the lock every time.

So, I really see no actual workaround that for a productive environment and it would be great if we heard from the team on the issue.

I am currently on the latest **.NET Core 2.1.402 SDK** and **2.1.4 Runtime** for my app.

Here is my factory for anyone interested to see and comment freely. I even try to connect on the new connection object in an infinite while loop, which is definitely a bad choice for code handling HTTP requests as well.

    public class EventStoreConnectionFactory : IEventStoreConnectionFactory
    {
        private readonly IOptions<BaseServiceConfig> _serviceOptions;
        private readonly IEventStoreLogger _logger;
        private readonly string _connectionString;
        private readonly string _connectionNameSuffix;
        private IEventStoreConnection _connection;
        private readonly static SemaphoreSlim _semaphoreSlim = new SemaphoreSlim(1, 1);

        public EventStoreConnectionFactory(
            IOptions<BaseServiceConfig> serviceOptions,
            IEventStoreLogger logger,
            string connectionString,
            string connectionNameSuffix = null)
        {
            _serviceOptions = serviceOptions ?? throw new ArgumentNullException(nameof(serviceOptions));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));
            _connectionNameSuffix = string.IsNullOrWhiteSpace(connectionNameSuffix)
                    ? ""
                    : $"-{connectionNameSuffix}";
        }

        public async Task<IEventStoreConnection> GetConnectionAsync(CancellationToken token = default)
        {
            await _semaphoreSlim.WaitAsync(token);
            try
            {
                if (_connection == null)
                {
                    _connection = await CreateAndConnectAsync();
                    return _connection;
                }

                var isDisposed = false;
                try
                {
                    _logger.Info($"Get EventStore Connection Requested, returning connection with name '{_connection.ConnectionName}'");
                }
                catch (ObjectDisposedException e)
                {
                    isDisposed = true;
                    _logger.Error(e, "Disposed EventStore Connection, will create a new one...");

                }

                if (isDisposed)
                {
                    _connection = await CreateAndConnectAsync();
                }

                return _connection;
            }
            finally
            {
                _semaphoreSlim.Release();
            }
        }

        internal async Task<IEventStoreConnection> CreateAndConnectAsync(CancellationToken token = default)
        {
            token.ThrowIfCancellationRequested();

            var builder = ConnectionSettings
                .Create()
                .KeepReconnecting()
                .UseCustomLogger(_logger);

            var connectionName = $"{_serviceOptions.Value.Service}-{_serviceOptions.Value.Version}{_connectionNameSuffix}";
            var connection = EventStoreConnection.Create(_connectionString, builder, connectionName);

            while (true)
            {
                token.ThrowIfCancellationRequested();
                try
                {
                    await connection.ConnectAsync();
                    break;
                }
                catch (Exception e)
                {
                    _logger.Error(e, "Error connecting to EventStore");
                }
            }

            return connection;
        }
    }

**Comment by jageall** [comment]
Hi @theofanis 

Thanks for the additional verification, can you tell me if this still happens in the 4.1.1-rc? There were a lot of changes in this release that may well have fixed this.  This project is community maintained until the main project releases a combined client so any assistance you can give will be much appreciated.

Thanks

**Comment by theofanis** [comment]
@jageall 
And I was about to confirm that the same behavior is exposed with 4.1.1-rc.

**Comment by jageall** [comment]
ok, I will try and get it reproduced as soon as I can

**Comment by hlubovac** [comment]
Instead of trying to revive the connection (it appears what you're experiencing is by-design), try to configure the client to not stop in its attempts to reconnect:

```
var settings = ConnectionSettings.Create();
settings.KeepReconnecting();
// the `settings` instance is what's handed off to the EventStoreConnection.Create method
```

So, if the service restarts, the client will keep trying to reconnect forever. When it finally does, it'll repeat any data-calls that it was in the middle of.

Also experiment with `settings.KeepRetrying();`. This seems to disable data-call timeouts that are evident while the service is starting up (in my experience, it takes 1-2 minutes for its reindexing to complete, during which data-calls are either put on hold or repeated by the client until they time-out).

**Comment by theofanis** [comment]
@hlubovac Ignore the code above. It was just an attempt to observe the disposed exception first hand when requesting a connection.

I have actually already removed the repeating code after seeing that the connect task always returns immediately, since the internal logic handler enqueues a connection task and returns.

I can set up a small app to showcase this actually, I may do it tomorrow. Reconnects never occur in Linux as is. Regardless of max attempts.

**Comment by theofanis** [comment]
@jageall Quick update on connection timeouts..

Increasing the connection timeout seems to allow for some breathing air before the disposed exception gets thrown after trying to connect the dropped subscription.

So, while playing with the default value on Windows is fine, on Linux I tried a timeout of 30 seconds. After getting the exception because of the subscription stop timeout (expected exception since on sub drop we have to call Stop()), the disposed exception is not thrown until the connection timeout period elapses. Increasing the value even higher makes this even more apparent.

So, if EventStore service is up before the connection timeout elapses, lo and behold, the connection gets connected again and the subscription is rolling on. Subsequent stops/starts of EventStore do not break things now as long as they occur in less than the timeout period.

I may have to go with an increased value like 30 seconds for the time being, since nothing else I tried seems to change the behavior. I know it's probably high, but if EventStore is down for that long then it's obvious the environment has gone unstable, a smaller value wouldn't change that.

**Comment by hlubovac** [comment]
I don't know if this relates, but reindexing of data - which seems to be a regular step of the service's startup routine - takes ~2 minutes on my almost-empty ES instance, while it takes ~15 minutes on our production instance. During that time - if I observed correctly - clients won't get data served.

**Comment by theofanis** [comment]
@hlubovac I haven't experienced this latency, but regardless, my subscriptions connect almost instantly when deploying on docker, with a compose that just started up the EventStore container.

Even this latency would be acceptable on some level considering the connection reconnect happens without the disposed errors.

**Comment by jen20** [comment]
I'll leave @jageall to comment on the connection issues, but worth noting @theofanis: re-indexing is an expected step on startup unless you have a million events, in which case the in-memory chunk of the index will be written to disk.

**Comment by hlubovac** [comment]
@theofanis 
Oh, I wasn't not complaining; just reporting what I observed.
Perhaps it's some startup-argument that I missed on ES that is causing this.

I see this within ES console-logs. I also run it within a docker container: TCP-listener starts, then it accepts the connection (on the other end, I had a client repeatedly probe), then the client sits (repeats data-calls, possibly, dunno) until the service is done indexing.

**Comment by hlubovac** [comment]
Try `host.docker.internal:1113` instead of that `ip:port` that you mentioned for the same-network, container-to-container communication. When the target container is stopped, it resolves to loopback-ip, making it possible for you to run a debuggable instance on your localhost (and have the source, in-container app talk to it).

**Comment by theofanis** [comment]
@hlubovac This setting works just fine, thanks for that, I normalized my `appsettings` for other to follow. And we are moving on with IPs when deploying. While this can be considered as closed by me, I guess it's still an issue, since it was never clear that this can be an issue and newcomers may fall on that. I hope this thread can be of help to anyone looking for more information.
