### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by bboyle1234** [EventStore/ClientAPI.NetCore#40]
The following exception was unhandled. Aysnc stuff was removed from the stack trace.

```
Connection 'TradingSilo-dev-tradingsilo1' was closed.

   at EventStore.ClientAPI.Internal.EventStoreNodeConnection.<ReadStreamEventsForwardAsync>d__26.MoveNext()

   at EventStore.ClientAPI.EventStoreStreamCatchUpSubscription.<ReadEventsInternalAsync>d__6.MoveNext()

   at EventStore.ClientAPI.EventStoreCatchUpSubscription.<LoadHistoricalEventsAsync>d__35.MoveNext()

   at EventStore.ClientAPI.Internal.EventStoreNodeConnection.<ReadStreamEventsForwardAsync>d__26.MoveNext()

   at EventStore.ClientAPI.EventStoreStreamCatchUpSubscription.<ReadEventsInternalAsync>d__6.MoveNext()

   at EventStore.ClientAPI.EventStoreCatchUpSubscription.<LoadHistoricalEventsAsync>d__35.MoveNext()
```

**Comment by bboyle1234** [comment]
```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Item Subscription VolatileSubscriptionOperation (db93cd15-5b7c-4954-9389-d6360c79839c): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 1, created: 05:28:30.348, last updated: 05:28:38.150 reached retries limit : 1)

Item Subscription VolatileSubscriptionOperation (db93cd15-5b7c-4954-9389-d6360c79839c): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 1, created: 05:28:30.348, last updated: 05:28:38.150 reached retries limit : 1

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.ClientAPI.EventStoreCatchUpSubscription.<SubscribeToStreamAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.ClientAPI.EventStoreCatchUpSubscription.<LoadHistoricalEventsAsync>d__35.MoveNext()

```

**Comment by bboyle1234** [comment]
```
System.AggregateException
  HResult=0x80131500
  Message=A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Item Operation ReadStreamEventsForwardOperation (59735d56-02f7-4a2e-8133-aa21ba75734e): Stream: $et-NadexAccount_Discovered, FromEventNumber: 1, MaxCount: 1024, ResolveLinkTos: True, RequireMaster: True, retry count: 1, created: 06:12:34.042, last updated: 06:12:40.207 reached retries limit : 1)
  Source=Apex.TradingSilo
  StackTrace:
   at Apex.TradingSilo.Program.<>c.<Main>b__5_1(Object s, UnobservedTaskExceptionEventArgs e) in D:\Projects\Apex.Grains\src\Apex.TradingSilo\Program.cs:line 84
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

Inner Exception 1:
RetriesLimitReachedException: Item Operation ReadStreamEventsForwardOperation (59735d56-02f7-4a2e-8133-aa21ba75734e): Stream: $et-NadexAccount_Discovered, FromEventNumber: 1, MaxCount: 1024, ResolveLinkTos: True, RequireMaster: True, retry count: 1, created: 06:12:34.042, last updated: 06:12:40.207 reached retries limit : 1
```

**Comment by jageall** [comment]
hi @bboyle1234, I am looking into this right now, 
could you confirm the version of the client that you are using please?

**Comment by bboyle1234** [comment]
Thank you. Yes, it's the latest nuget release 4.1.1-rc1

**Comment by bboyle1234** [comment]
Hi @jageall, did you manage to find anything? 
The issue seems to happen after the program has been paused in the debugger. 
Here are the settings I used to create the connection: 

```csharp
                        var timeout = Debugger.IsAttached ? TimeSpan.FromMinutes(30) : TimeSpan.FromSeconds(1);
                        var retries = Debugger.IsAttached ? 1000 : 1;
                        var settings = ESConnectionSettings.Create()
                            .UseCustomLogger(Log.AsEventStoreLogger())
                            .LimitReconnectionsTo(1)
                            .WithConnectionTimeoutOf(timeout)
                            .SetOperationTimeoutTo(timeout)
                            .LimitAttemptsForOperationTo(retries)
                            .LimitRetriesForOperationTo(retries)
                            .PerformOnMasterOnly();

```

**Comment by bboyle1234** [comment]
In case this helps, I was able to "remove" the problem by increasing `LimitReconnectionsTo(100)`.

**Comment by gregoryyoung** [comment]
This actually makes sense given your settings above ^^^ let me explain a bit (sorry for being late on the explanation).

You have limited reconnections to 1 time. You also have timeouts set which you might think would make everything work but it doesn't. There are also heartbeats on the connection which are sent occasionally to make sure it is alive. 

Most likely and you can send me a full client log so I can verify it if you want, you are hitting client timeouts due to heartbeats...

**Comment by bboyle1234** [comment]
That sounds about right, and I'll follow up with you on that. Perhaps I just need to change a heartbeat setting while I'm debugging. 
The EventStoreConnection is failing to observe an exception that is raised within itself in this particular situation ... do you see that as evidence of a possible flaw?
